### ISSUE TITLE
nuget packages fail

### ISSUE THREAD

**Issue by DarylOliver** [viciousviper/DokanCloudFS#15]
when install nuget packages in cloudfs everything works the build and everything succeeds but when copying gateways to dokan compile succeeds but still get client id errors

do the cloudfs gateways include keys or a way to authenticate? This is really getting on my nerves and I can't directly install cloudfs to dokancloudfs because it crashes how do I authenticate without downloading my own keys or any of that?

**Comment by viciousviper** [comment]
Hi DarylOliver,

I apologize for my prolonged silence - I've been traveling abroad and had no access to either GitHub or my build environment.

That said, I'll have some time to spare in the next couple of days to iron out the problems with running a non locally-built DokanCloudFS.

What I've managed to get working so far is the result of the following steps:

0. Install Dokany 1.0.0-RC3
1. Build the *CloudFS* solution with whatever entries there are in 'Secrets.cs' - the result will be partially overwritten later in step 4.
2. Copy the build output of the *CloudFS* solution into the *Libraries* directory of the *DokanCloudFS* solution
3. Build the *DokanCloudFS* solution
4. Replace any cloud service gateway - obviously *IgorSoft.CloudFS.Gateways.GDrive.dll* in your case - with the variant contained in a downloaded NuGet package of *cloudfs.1.0.6-alpha.nupkg*. This will provide the API keys that you are currenly missing.
5. Adjust *IgorSoft.DokanCloudFS.Mounter.exe.config* as required
6. Run *IgorSoft.DokanCloudFS.Mounter.exe* from its build directory in an administrative *cmd.exe*
7. You should see a web browser window being opened and asking you to login to your GDrive account
8. After successfully logging in and allowing *CloudFS* access to your GDrive, you should now see a new virtual drive according to your configuration in step 5.

Please let me know if this works now - or else what errors you are getting at what step.

**Comment by DarylOliver** [comment]
what do I adjust the config to also where I get the secrets entries from?

![image](https://cloud.githubusercontent.com/assets/11663819/16091885/84bf0014-332d-11e6-9d23-89d547404f9e.png)

**Comment by DarylOliver** [comment]
![image](https://cloud.githubusercontent.com/assets/11663819/16091902/9dd97b92-332d-11e6-90f4-3a02c276c7ad.png)

thats the mounter configuration file

**Comment by viciousviper** [comment]
Ok, this discussion is leading nowhere.
If you actually want to understand where the entries in the `Secrets.cs` files come from I invite you to re-read the passage [Local Compilation](https://github.com/viciousviper/CloudFS#local-compilation) in [CloudFS/README.md](https://github.com/viciousviper/CloudFS/blob/master/README.md) with special emphasis on the **Application registration / configuration URL** associated with the **Cloud storage service** you want to use.
The whole process has been summarized in the new paragraph [LocalCompilation/Using your own API keys](https://github.com/viciousviper/DokanCloudFS/blob/develop/README.md#using-your-own-api-keys) in *README.md*.

If you are less tech-savvy and just want to get things to work you might as well try my latest checkin b15b0be to the *develop* branch - this will allow you a much simpler approach documented in [LocalCompilation/Using pre-configured API keys from the CloudFS NuGet packages](https://github.com/viciousviper/DokanCloudFS/blob/develop/README.md#using-pre-configured-api-keys-from-the-cloudfs-nuget-packages) also in *README.md*.

Now I'm at my wits' end.

**Comment by DarylOliver** [comment]
Hi appologies if I caused any undo stress actaully I'm usually ok with compiling software it just the secrets part that through me since the google api doesn't simply let you download needed files and the documentation on putting those in the secrets file was vague since no matter how i placed them it would crash any thanky you for making the program install cloudfs itself during build process.

**Comment by viciousviper** [comment]
Glad that it appears to have worked for you.
Thanks for your patience and sorry for letting my own impatience show - this project is still in its alpha phase, so a measure of rough edges and unmasked complexity is to be expected.

I'm closing this issue now - feel free to comment back on any other issues you may encounter.
