### ISSUE TITLE
Wasted an entire 16 hours trying to use this library

### ISSUE THREAD

**Issue by oldmud0** [viciousviper/DokanCloudFS#18]
I don't mean to come off as rude, but I'm very distraught because I intended to use this library for a local hackathon, and it has been an absolute mess. Literally every step of the way has been riddled with bugs and other quirks and undefined behavior, even when following the instructions to the letter and trying it on two different Windows 7 x64 machines. Needless to say that I wasted my time trying to make a frontend out of this library. Maybe you can figure out whether the library hates me or if it's just that unstable.

The first problem was when DokanCloudFS failed to load assemblies when I set the build configuration to NuGet-Signed. If I tried cleaning the build, it would still error out. If I tried changing the build config back to regular NuGet, yet again it would throw the exact same exception. The solution was to nuke the entire project, keep it in the default configuration and **never touch it again**. This alone cost me a few hours to figure out.

And alas, very shortly later, more problems arose. My mounted Google Drive appeared as a drive, but all interactivity with it was completely blocked, thanks to a vague exception thrown repeatedly as shown in the console:

```
Exception thrown: 'Google.GoogleApiException' in mscorlib.dll
...
Exception thrown: 'Google.GoogleApiException' in Google.Apis.dll
Exception thrown: 'System.IO.InvalidDataException' in SharpAESCrypt.dll
...
```
Absolutely no stack trace and Visual Studio did not even bother to break.

And this was after I had compiled CloudFS, put in secret keys for GDrive, copied the output DLLs to the DokanCloudFS Library folder, and assured that it had access to the Drive API by turning it on in the console, and waited a few minutes for it to "enable".

So I said, screw it! Let's use OneDrive instead, thinking that somehow it would ease my pain. Nope. Same spiel. Except Microsoft was taking me to some OAuth2 auth link that would just take me to a blank page. After a bit of research I found out that I had to add "mobile" as a platform in order for me to even have an OAuth2 login page. Okay, so when it asks me, "Let this app access your info?" and the usual permissions and I click "yes," ....it just opens another browser window to do the exact same thing. I click yes again, and the window reappears ad infinitum. And instead of the `GoogleApiException` I get a `System.Security.Authentication.AuthenticationException in mscorlib.dll` along with a `System.AggregateException` which VS *should* be breaking to tell me about, but it's not doing squat.

By this time I'm forgetting about even running the DokanCloudFS.Mounter example and instead just building hacks to bridge the frontend with the library, using the mounter program as an example because there's absolutely no documentation that comes with it.

And as of the time of the writing of this issue, I've spent sixteen hours trying to get all this to work just to make a frontend that will mount OneDrive, Google Drive, etc. in unison.

I don't ever complain publicly about things, but I am so angry that I wasted all of this time trying to use a library that's not even properly documented to try to make some legitimate software. Oops my fault, sorry I should have gone back to making Java games because I obviously don't know what I'm doing.

**Comment by js69** [comment]
I wouldn't want to read anything you write when you are intentionally rude.

If you have questions about something or problems with a lack of documentation, wouldn't the logical first step be to ask the author?

**Comment by oldmud0** [comment]
Turnaround time would be too long given the limited time I have.

Look, accept it, I wasted my time and it's not his fault, it's *my* fault for being such an idiot and choosing some library off the corner of the internet that's not even documented or well tested.
