### ISSUE TITLE
build error referencing wrong version

### ISSUE THREAD

**Issue by Band-Aid** [viciousviper/DokanCloudFS#21]
Hi,
Trying to build the solution I am getting the following error.
Doing some digging around I noticed the build is referencing the wrong version.
It's looking for clouldFS1.0.7 but nu-get has downloaded v1.0.8

I think the dependencies have to be updated to use v1.0.8

Error Command "xcopy /D /Y C:\Users\daish\Downloads\DokanCloudFS-master\DokanCloudFS-master\packages\CloudFS.1.0.7-alpha\lib\net46\Gateways\IgorSoft.CloudFS.Gateways.*.dll.config ."  with error code 4	DokanCloudFS.Gateways

**Comment by viciousviper** [comment]
Well found, thanks for notifying me.

Please try [this](https://github.com/viciousviper/DokanCloudFS/releases/tag/v1.0.9-alpha).
