### ISSUE TITLE
Support for Java.

### ISSUE THREAD

**Issue by SyCode7** [viciousviper/DokanCloudFS#25]
Hi, is there currently support for Java  ... or some bindings that support use of Java for your library ? For example [jclouds](https://jclouds.apache.org/) is a multi-cloud java library that supports several cloud service providers. This could be a good feature if possible since there is  a growing interest in using virtual file systems for cloud storage.

**Comment by viciousviper** [comment]
Hi SyCode7,

I don't have any plans related to Java.
Perhaps you could elaborate on your envisioned use case?

Cheers, vv

**Comment by SyCode7** [comment]
Hi vv,

Many thanks for the great work you are doing and for your response.
We currently have a multi-cloud application for storing files across several cloud storage services.
One advantage of our application is we can encrypt and do other security stuff before uploading 
to the clouds. We also maintain a unified root directory, which we plan to transition to a VFS like yours.
However, we use the Java APIs provided by the cloud providers, so integrating your framework will require some plumbing. Do you have some suggestions on this possibility ? 

Thanks.

**Comment by JuniorJPDJ** [comment]
You may just use dokany with java bindings or even fuse for multiplatform support

**Comment by viciousviper** [comment]
Hi @SyCode7,

I'm afraid I can't help you with your project. Matching up a Windows system driver with a .NET handler is complicated enough as it is, and I prefer to keep the set of disparate runtime environments involved within reasonable limits. Now if there was an attractive cloud storage service that could only be accessed through a Java API - or if you need special extended features that you can't get the .NET API developers to include in their parts - that would be something different, but I wouldn't see much sense in replacing perfectly well working .NET APIs with their Java counterparts.
As it is, you can always implement a compatible cloud service gateway yourself and plug in it into the *DokanCloudFS* mounter, or take @JuniorJPDJ's advice and attach directly to dokany.

**Comment by SyCode7** [comment]
Hi @vv, thanks I do appreciate. @JuniorJDPJ, we are currently trying out Dokan Java, but since it is not maintained there are a number of bugs we have to take care of.
