### ISSUE TITLE
Yandex causing error

### ISSUE THREAD

**Issue by acosonic** [viciousviper/DokanCloudFS#27]
Hi, I had hard time compiling and running, eventually figured out to change Mounter's Program.cs by adding

 ```
 } catch (ReflectionTypeLoadException ex) {
                Console.Error.WriteLine($"{ex.GetType().Name}: {ex.Message}");
                foreach(Exception ex2 in ex.LoaderExceptions)
                {
                    Console.Error.WriteLine($"{ex2.GetType().Name}: {ex2.Message}");
                }
                return -1;
            } 
```

Above:

```
catch (Exception ex) {
                Console.Error.WriteLine($"{ex.GetType().Name}: {ex.Message}");
                return -1;
```
And figured out error from
_ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information._

To:
_ken=1f35af1d8b0c0a75' or one of its dependencies. The system cannot find the file specified.
FileNotFoundException: Could not load file or assembly 'YandexDisk.Client, Version=1.0.8.0, Culture=neutral, PublicKeyToken=1f35af1d8b0c0a75' or one of its dependencies. The system cannot find the file specified._

**Comment by viciousviper** [comment]
Hi @acosonic,

thanks for reporting this - I'll look into it.
