### ISSUE TITLE
Can this be used with directory mounts?

### ISSUE THREAD

**Issue by mikesmiffy128** [viciousviper/DokanCloudFS#30]
Hello, this tool looks like quite a nice way to access online storage (thanks!). However, I don't really like the idea of polluting the system with fake drives, and would much rather have something like ~/clouds with subdirectories for each mount. This would also avoid the problem of there only being 26 drive letters.

**Comment by viciousviper** [comment]
Hi @mikesmiffy128,

presently I only support virtual drives. AFAIK the base technology behind my tools (which is of course [Dokany](https://github.com/dokan-dev/dokany)) does not support arbitrary directories as mount points, but I'd have to check again to be sure.
I might be able to mount several virtual file systems as top-level directories of a specific virtual drive (i.e. *V:\OneDrive\\* and *V:\Mega\\*) - would this be of any value to you?

As an aside - do you really see a problem in having "only" 26 drive letters (or maybe more like 20) available for cloud volumes?

**Comment by viciousviper** [comment]
.., turns out I am mistaken and Dokany is very much able to use arbitrary dictionaries as mount points.

I'll look into this.

**Comment by mikesmiffy128** [comment]
Ah, great. I was sure it was possible and was just looking for the relevant information but it looks like you beat me to it. :) Regarding "only 26," it's not really a problem for me but it is foreseeable that someone somewhere with a lot of hard disks, network mounts etc would want to avoid running out of letters.

Thanks for looking into it! 👍

**Comment by viciousviper** [comment]
Unfortunately, all is not as easy as it seems. :disappointed:

While the *dokany* docs clearly state that mount points can be (empty) NTFS directories, I've had no success with actually mounting to anything but a full drive letter.
This is both from within *DokanCloudFS* and from the C-based `mirror.exe` sample provided with dokany. The latter just gives me a "Can't assign a drive letter" from calls like
    `mirror.exe /r C:\Temp /l D:\Temp\Dokan\Mount`
whereas
    `mirror.exe /r C:\Temp /l T:`
works as expected.

I'll try contacting the *dokany* devs to find out what the actual matter is.

**Comment by viciousviper** [comment]
Long story short: Directory mount points basically work with only minimal changes to DokanCloudFS.
You will, however, have to pay very close attention to your intended mount point being an existing and empty directory. If the *dokany* driver fails to mount to directory only once, it will refuse to mount to any directory mount point - even legitimate ones - until the next reboot.
I'll commit the required changes shortly.

**Comment by mikesmiffy128** [comment]
:+1:

**Comment by Rondom** [comment]
@viciousviper  That sounds like a bug. Maybe try to reproduce it with the mirror and report it.

**Comment by viciousviper** [comment]
Hi @Rondom,
I was able to reproduce this exact behaviour with `mirror.exe`.
Will fill the required forms for a dokany bug report sometime later.
