### ISSUE TITLE
OneDrive Auth Error

### ISSUE THREAD

**Issue by shlatchz** [viciousviper/DokanCloudFS#6]
When I try to run the mounter with onedrive, an authentication window pops up, but instead of asking for my credentials, I get the following error in the browser:
"Cloud not complete your request.
Your Microsoft account is experiencing some technical difficulties. Please try again later"

I tried clearing my browser cache and it didn't help.

**Comment by viciousviper** [comment]
I'm assuming that you compiled the *CloudFS* solution from sources.
If so, could you please check if you inserted valid credentials for a registered OneDrive application in `Secrets.cs` before compiling the *CloudFS* solution? Invalid credentials are one possible reason for the error message you quoted.

**Comment by shlatchz** [comment]
I followed this to get a client id and secret:

	To register your app to connect with OneDrive, you'll need a Microsoft account.

	Go to the Microsoft account Developer Center.
	When prompted, sign in with your Microsoft account credentials.
	Choose Create application.
	Enter your app's display name and choose the app's primary language.
	Read the Live Connect terms of use and the Privacy and Cookies statement, and then choose I accept to accept the terms of use.
	After you've completed these steps, a client ID and client secret are created for your app. 

and I added them to Secrets.cs, but I still can't authenticate. Now, I have a different error:
"Something went wrong and we can't log you in at this moment.
Please try again later"

**Comment by viciousviper** [comment]
Could you please check again with the pre-built NuGet packages?
Only thing I can think of is that something went wrong when you transferred the credentials into `Secrets.cs` - like additional blank characters or a leftover angle bracket - or maybe your application registration has insufficient rights to access the OneDrive files.

**Comment by viciousviper** [comment]
Closed as obsolete.
Beginning with version 1.0.6-alpha DokanCloudFS uses a pre-configured CloudFS NuGet package
