### ISSUE TITLE
Profetional support

### ISSUE THREAD

**Issue by fitandre** [viciousviper/DokanCloudFS#8]
Dear Viciousviper,

Can we hire som profetional support for DokanCloudFS?

Regards,

Andre Meyer Pflug
andre@ddeskllc.com

**Comment by viciousviper** [comment]
There's no professional support as such that I know of. Maybe you could be a bit more specific as to your requirements.

And BTW, why is it that the Net does not seem to know neither you nor the company you claim to work for nor its URL?

**Comment by viciousviper** [comment]
Closed as bogus.
